replicaCount: 2
image:
  repository: nginx
  tag: "1.23.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

nodeSelector: {}

tolerations: []

affinity: {}
